### ISSUE TITLE
1.3.2, 1.3.3 broken on gulp 3.9.1

### ISSUE THREAD

**Issue by JoeOrtiz** [bingnz/gulp-less-changed#12]
When running on gulp 3.9.1, somehow 1.3.2, and 1.3.3 fails with:

```
module.js:544
    throw err;
    ^

Error: Cannot find module 'gulp-less-changed'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/site/client/gulpfile.js:10:17)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

1.3.1 works though.

**Comment by bingnz** [comment]
@JoeOrtiz thanks for letting me know. I've been having some problems with the Travis build since I updated the semantic release version and I haven't really had time to figure out how to make it work properly. 1.3.4 should be OK; please give it a try. And thanks again!

**Comment by JoeOrtiz** [comment]
Tested that it does work now.

Many thanks!
